language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

env:
  - CODECLIMATE_REPO_TOKEN=e667d2e372ff362871a8955801a78e05765d4e49fa3ac2958bcd00a9508bdf0f

after_success:
  - npm run-script coverage
  - npm run-script codeclimate

